# dataset
data_path: "./data"
# filename: "sdwpf_baidukddcup2022_full.csv"
# filename: "wtbdata_245days.csv"
filename: "wtbdata_245days_new.csv"
input_len: 144 
output_len: 288
# var_len: 13
var_len: 10
capacity: 134
patient: 2 

# train_days: 153 
# val_days: 16 
# test_days: 15 
# total_days: 184 

# train_days: 196
# val_days: 25
# test_days: 24
# total_days: 245

train_days: 214
val_days: 16
test_days: 15
total_days: 245

num_workers: 8
epoch: 10 
batch_size: 128 
output_path: "./output/baseline_"
log_per_steps: 100
lr: 0.0003

# Model
model:
    hidden_dims: 128 
    nhead: 8
    dropout: 0.5
    encoder_layers: 2
    decoder_layers: 2

loss:
    name: "FilterMSELoss"
