# dataset
data_path: "./data"
# filename: "sdwpf_baidukddcup2022_full.csv"
filename: "wtbdata_245days.csv"
# filename: "wtbdata_245days_new.csv"
# filename: "all_data.csv"
input_len: 144 
output_len: 288
# var_len: 13
# var_len: 10
var_len: 6
capacity: 134
patient: 2 

# train_days: 214 
# val_days: 16 
# test_days: 15 
# total_days: 245 

train_days: 230 
val_days: 15 
test_days: 0
total_days: 245 

num_workers: 8
epoch: 10 
batch_size: 256 
output_path_raw: "./output/baseline"
log_per_steps: 100
lr: 0.0005

# Model
model:
    hidden_dims: 256 
    nhead: 8
    dropout: 0.5
    encoder_layers: 2
    decoder_layers: 2

loss:
    name: "FilterMSELoss"