# dataset
data_path: "./data"
# filename: "sdwpf_baidukddcup2022_full.csv"
filename: "wtbdata_245days.csv"
# filename: "wtbdata_245days_0629.csv"
# filename: "wtbdata_245days_0629_p5.csv"
# filename: "wtbdata_245days_0629_p20.csv"
# filename: "wtbdata_245days_0629_single20.csv"
# filename: "wtbdata_245days_0630_p10.csv"
# filename: "wtbdata_245days_0630_p20.csv"
# filename: "all_data_water.csv"
input_len: 144
output_len: 288
# var_len: 13
# var_len: 10
# feature numbers
var_len: 5
capacity: 134
patient: 2

# train_days: 214 
# val_days: 16 
# test_days: 15 
# total_days: 245 

train_days: 230 
val_days: 15 
test_days: 0
total_days: 245 

num_workers: 16
epoch: 20 
batch_size: 64 
output_path: "./output/baseline_st2"
log_per_steps: 100
lr: 0.0003

# Model
model:
    hidden_dims: 512 
    nhead: 8
    dropout: 0.5
    encoder_layers: 2
    decoder_layers: 1

loss:
    name: "FilterMSELoss"